"""Choose the blog articles that belong under each strategy page.

Matching on bare substrings was no good -- "ses" is inside "businesses" and
"processes", and "military" turned up wherever "civilian market" appeared. So
terms are matched on word boundaries, a hit in the title counts for three times
one in the excerpt, and a post has to clear a threshold to be listed at all.

Off-audience terms are subtracted as well. Without that, the corporate page
filled up with government-to-private pieces, because almost every article here
mentions the private sector somewhere.

Writes the chosen slugs into src/data/strategy-articles.js.
"""
import io
import json
import os
import re
import sys

repo = sys.argv[1]

s = io.open(os.path.join(repo, 'src/data/posts.js'), encoding='utf-8').read()
posts = json.loads(s[s.index('['):s.rindex(']') + 1])

B = r'\b'

GROUPS = {
    'government': [
        (B + r'government' + B, 3), (B + r'federal' + B, 3),
        (B + r'public[- ]sector' + B, 2), (B + r'public service' + B, 3),
        (B + r'gs-1[0-5]' + B, 3), (B + r'civil service' + B, 3),
        (B + r'agency' + B, 2), (B + r'ex-fed' + B, 3), (B + r'bureau\w*' + B, 2),
    ],
    'ses': [
        (B + r'ses' + B, 5), (B + r'ecqs?' + B, 5), (B + r'tqs?' + B, 4),
        (B + r'senior executive service' + B, 5), (B + r'opm' + B, 4),
        (B + r'executive core' + B, 4), (B + r'gs-15' + B, 3),
        (B + r'senior executives?' + B, 2), (B + r'executive leadership' + B, 2),
        (B + r'highest level' + B, 2),
    ],
    'military': [
        (B + r'military' + B, 4), (B + r'veterans?' + B, 3),
        (B + r'service members?' + B, 3), (B + r'army' + B, 3),
        (B + r'navy' + B, 3), (B + r'air force' + B, 3), (B + r'marine' + B, 3),
        (B + r'uniform' + B, 2), (B + r'deployment' + B, 2),
        (B + r'command' + B, 2), (B + r'rank' + B, 2),
    ],
    'corporate': [
        (B + r'corporate' + B, 4), (B + r'c-suite' + B, 4), (B + r'board' + B, 3),
        (B + r'industry' + B, 2), (B + r'hiring committees?' + B, 3),
        (B + r'promotion' + B, 2), (B + r'executive' + B, 2),
        (B + r'leadership' + B, 2), (B + r'interview\w*' + B, 2),
        (B + r'negotiat\w*' + B, 2), (B + r'salary' + B, 2),
        (B + r'linkedin' + B, 2), (B + r'personal brand\w*' + B, 2),
    ],
}

PENALTY = {
    'corporate': [(B + r'government' + B, 4), (B + r'federal' + B, 4),
                  (B + r'military' + B, 4), (B + r'gs-1[0-5]' + B, 4),
                  (B + r'veterans?' + B, 3)],
    'government': [(B + r'military' + B, 3)],
    'military': [],
    'ses': [(B + r'military' + B, 2)],
}

THRESHOLD = 5
LIMIT = 8

out = {}
allmatches = {}
for group, terms in GROUPS.items():
    scored = []
    for p in posts:
        title, excerpt = p['title'].lower(), p['excerpt'].lower()
        score = 0
        for pat, weight in terms:
            if re.search(pat, title):
                score += weight * 3
            elif re.search(pat, excerpt):
                score += weight
        for pat, weight in PENALTY.get(group, []):
            if re.search(pat, title):
                score -= weight * 3
            elif re.search(pat, excerpt):
                score -= weight
        if score >= THRESHOLD:
            scored.append((score, p['date'], p['slug'], p['title']))

    # Strongest first; among equals, the most recent.
    scored.sort(key=lambda t: (-t[0], t[1]), reverse=False)
    scored = sorted(scored, key=lambda t: (-t[0], [-ord(c) for c in t[1]]))
    chosen = scored[:LIMIT]
    out[group] = [c[2] for c in chosen]
    # The strategy pages show a short list; the blog filter shows the lot.
    allmatches[group] = [c[2] for c in scored]
    print('\n%s -- %d over threshold, listing %d' % (group.upper(), len(scored), len(chosen)))
    for sc, date, slug, title in chosen:
        print('   %3d  %s  %s' % (sc, date, title[:64]))

path = os.path.join(repo, 'src/data/strategy-articles.js')
with io.open(path, 'w', encoding='utf-8', newline='\n') as f:
    f.write('/* Which articles sit under each strategy page.\n'
            '   Generated by scripts/pick-strategy-articles.py from the blog index --\n'
            '   rerun it after publishing, or edit by hand to pin a particular piece. */\n\n')
    f.write('export const strategyArticles = ')
    f.write(json.dumps(out, ensure_ascii=False, indent=2))
    f.write(';\n\n')
    f.write('/* Every article that matched, for the category filter on the blog. */\n')
    f.write('export const articleCategories = ')
    f.write(json.dumps(allmatches, ensure_ascii=False, indent=2))
    f.write(';\n')
print('\nwrote', path)
